name: lunacd-gnucash
title: GnuCash
license: GPL-2.0+
base: core24
version: '5.16'
summary: GnuCash Double-Entry Accounting Program
description: |
  GnuCash is a personal and small business double entry accounting application.
icon: gui/gnucash-256x256.png
website:
  - https://www.gnucash.org/
source-code:
  - https://github.com/gnucash/gnucash.git
  - https://github.com/lunacd/gnucash-snap
issues:
  - https://github.com/lunacd/gnucash-snap/issues
contact:
  - liu.haowen.andy@gmail.com

grade: stable
confinement: strict

parts:
  gnucash:
    plugin: cmake
    source: https://github.com/gnucash/gnucash.git
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "--install-prefix /usr"
      - "-DCMAKE_INSTALL_SYSCONFDIR=/usr/etc"
    build-packages:
      - guile-3.0-dev
      - libaqbanking-dev
      - libdbd-sqlite3
      - libdbi-dev
      - libboost-atomic-dev
      - libboost-chrono-dev
      - libboost-container-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-locale-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-thread-dev
      - libfinance-quote-perl
      - libgtest-dev
      - libgwengui-gtk3-dev
      - libofx-dev
      - libxslt-dev
      - swig
      - xsltproc
    stage-packages:
      - guile-3.0-libs
      - libaqbanking44
      - libboost-locale1.83.0
      - libboost-filesystem1.83.0
      - libboost-program-options1.83.0
      - libdbi1t64
      - libdbd-sqlite3
      - libfinance-quote-perl
      - libgwengui-gtk3-79t64
      - libofx7t64
      - libosp5
      - libxmlsec1t64
      - libxslt1.1
    stage:
      # libxslt is used but not libexslt, so we remove libexslt from the stage
      - -usr/lib/*/libexslt.so*
    build-environment:
      - PERL5LIB:  "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl5/5.38/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.38.2/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl/5.38/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl/5.38.2/"
    override-pull: |
      craftctl default
      git am "${CRAFT_PROJECT_DIR}/patches/0001-Use-ORIGIN-in-RPATH.patch"
      git am "${CRAFT_PROJECT_DIR}/patches/0002-Remove-development-version-warning.patch"

apps:
  gnucash:
    command: usr/bin/gnucash
    extensions:
      - gnome
    desktop: usr/share/applications/gnucash.desktop
    environment:
      GUILE_LOAD_PATH: "$SNAP/usr/share/guile/3.0:$SNAP/usr/share/guile/site/3.0:$GUILE_LOAD_PATH"
      GUILE_LOAD_COMPILED_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/guile/3.0/ccache:$GUILE_LOAD_COMPILED_PATH"
      PERL5LIB:  "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl5/5.38/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.38.2/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl/5.38/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl/5.38.2/"
    plugs:
      - home

lint:
  ignore:
    - library:
        # Dynamically loaded for reports using `(load-extension)`
        - usr/lib/**/libgnc-expressions-guile.so